package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/charmbracelet/lipgloss"
)

func cmdBrief(args []string) {
	jsonOutput := false
	for _, a := range args {
		if a == "--json" {
			jsonOutput = true
		}
	}

	session, err := loadSession()
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}

	if jsonOutput {
		title := session.AssessmentTitle
		if title == "" {
			title = "Assessment Task"
		}

		out := map[string]interface{}{
			"title":             title,
			"taskBrief":         session.TaskBrief,
			"timeLimitMinutes":  session.TimeLimitMinutes,
			"workspace":         session.TaskRoot,
			"setupInstructions": session.SetupInstructions,
		}

		if session.TimeLimitMinutes > 0 && !session.StartedAt.IsZero() {
			elapsed := time.Since(session.StartedAt)
			remaining := time.Duration(session.TimeLimitMinutes)*time.Minute - elapsed
			if remaining < 0 {
				remaining = 0
			}
			out["remainingMinutes"] = int(remaining.Minutes())
		}

		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		_ = enc.Encode(out)
		return
	}

	// Human-readable output (original).
	titleStyle := lipgloss.NewStyle().
		Bold(true).
		Foreground(cStrong)

	briefStyle := lipgloss.NewStyle().
		Foreground(cBody).
		Width(68)

	metaStyle := lipgloss.NewStyle().
		Foreground(cMuted)

	boxStyle := lipgloss.NewStyle().
		Border(lipgloss.RoundedBorder()).
		BorderForeground(lipgloss.Color("#22c55e")).
		Padding(1, 2).
		Width(74)

	// No title: assessment titles are auto-derived from upstream issue text
	// which leaks the answer (see project_audit_may2026_results.md). The brief
	// itself is the single source of truth for what the candidate must do.
	var content strings.Builder
	content.WriteString(titleStyle.Render("Task"))
	content.WriteString("\n\n")

	// Task brief
	if session.TaskBrief != "" {
		wrapped := strings.Join(wordWrap(session.TaskBrief, 68), "\n")
		content.WriteString(briefStyle.Render(wrapped))
		content.WriteString("\n")
	}

	// Time info
	content.WriteString("\n")
	if session.TimeLimitMinutes > 0 {
		elapsed := time.Since(session.StartedAt)
		remaining := time.Duration(session.TimeLimitMinutes)*time.Minute - elapsed
		if remaining < 0 {
			remaining = 0
		}

		content.WriteString(metaStyle.Render(fmt.Sprintf("⏱  Time limit: %d minutes", session.TimeLimitMinutes)))
		if !session.StartedAt.IsZero() {
			content.WriteString("\n")
			if remaining > 0 {
				content.WriteString(metaStyle.Render(fmt.Sprintf("⏳  Remaining: ~%d minutes", int(remaining.Minutes()))))
			} else {
				content.WriteString(lipgloss.NewStyle().Foreground(lipgloss.Color("#ef4444")).Bold(true).Render("⏳  Time limit exceeded"))
			}
		}
	}

	// Workspace
	if session.TaskRoot != "" {
		content.WriteString("\n")
		content.WriteString(metaStyle.Render(fmt.Sprintf("📁  Workspace: %s", session.TaskRoot)))
	}

	fmt.Println()
	fmt.Println(boxStyle.Render(content.String()))
	fmt.Println()
	fmt.Println(metaStyle.Render("  Tip: This info is also in TASK.md in your workspace."))
	fmt.Println()
}

// writeTaskFile creates TASK.md in the workspace root with the assessment brief.
// No title heading: assessment titles are auto-derived from upstream issue
// text which leaks the answer (see project_audit_may2026_results.md). The
// brief itself is the single source of truth for what the candidate must do.
func writeTaskFile(workspacePath string, session Session, brief string, timeLimitMinutes int) {
	if workspacePath == "" || brief == "" {
		return
	}

	var content strings.Builder
	content.WriteString("# Task\n\n")
	content.WriteString(brief)
	content.WriteString("\n")

	if timeLimitMinutes > 0 {
		content.WriteString(fmt.Sprintf("\n---\n\n**Time limit:** %d minutes\n", timeLimitMinutes))
	}

	if session.SetupInstructions != "" {
		content.WriteString(fmt.Sprintf("\n## Setup\n\n%s\n", session.SetupInstructions))
	}

	content.WriteString("\n---\n\n")
	content.WriteString("*This file was generated by Promptster. You can reference it anytime, or run `promptster brief` in your terminal.*\n")

	taskPath := filepath.Join(workspacePath, "TASK.md")
	// Don't overwrite if it already exists (candidate might have edited it)
	if _, err := os.Stat(taskPath); err == nil {
		return
	}
	_ = os.WriteFile(taskPath, []byte(content.String()), 0o644)
}
