package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/charmbracelet/lipgloss"
)

// cmdBrief shows the assessment brief. By default it opens the live brief
// viewer (countdown + structured task doc) in a brand-new terminal window so
// it stays visible next to the candidate's editor.
//
//	promptster brief          open the viewer in a new terminal window
//	promptster brief --here   run the viewer in this terminal
//	promptster brief --plain  print once, no interactivity (also the no-TTY path)
//	promptster brief --json   machine-readable output
//	promptster brief --demo   preview the viewer with sample content (no session)
func cmdBrief(args []string) {
	var jsonOutput, here, plain, demo bool
	for _, a := range args {
		switch a {
		case "--json":
			jsonOutput = true
		case "--here", "--inline":
			here = true
		case "--plain":
			plain = true
		case "--demo":
			demo = true
		}
	}

	var session Session
	var brief Brief
	if demo {
		session, brief = demoBriefSession()
	} else {
		s, err := loadSession()
		if err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			os.Exit(1)
		}
		session = s
		brief = resolveBrief(s)
	}

	if jsonOutput {
		printBriefJSON(session, brief)
		return
	}

	if plain || !stdoutIsTerminal() {
		printBriefStatic(session, brief)
		return
	}

	if here || demo {
		if err := runBriefTUI(session, brief); err != nil {
			printBriefStatic(session, brief)
		}
		return
	}

	// Default: pop the viewer in its own terminal window so the brief stays
	// accessible while the candidate works. Fall back to inline on failure.
	if err := openBriefWindow(); err != nil {
		if err := runBriefTUI(session, brief); err != nil {
			printBriefStatic(session, brief)
		}
		return
	}

	muted := lipgloss.NewStyle().Foreground(cMuted)
	fmt.Println()
	fmt.Println("  " + lipgloss.NewStyle().Foreground(cStrong).Render("Opened the brief in a new terminal window."))
	fmt.Println("  " + muted.Render("Keep it on a corner of your screen — the countdown updates live."))
	fmt.Println("  " + muted.Render("Prefer it here? Run: promptster brief --here"))
	fmt.Println()
}

func printBriefJSON(session Session, brief Brief) {
	title := session.AssessmentTitle
	if title == "" {
		title = "Assessment Task"
	}

	out := map[string]interface{}{
		"title":             title,
		"taskBrief":         session.TaskBrief,
		"brief":             brief,
		"timeLimitMinutes":  session.TimeLimitMinutes,
		"workspace":         session.TaskRoot,
		"setupInstructions": session.SetupInstructions,
	}

	if session.TimeLimitMinutes > 0 && !session.StartedAt.IsZero() {
		elapsed := time.Since(session.StartedAt)
		remaining := time.Duration(session.TimeLimitMinutes)*time.Minute - elapsed
		if remaining < 0 {
			remaining = 0
		}
		out["remainingMinutes"] = int(remaining.Minutes())
	}

	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	_ = enc.Encode(out)
}

// stdoutIsTerminal reports whether stdout is a terminal (vs piped/redirected).
func stdoutIsTerminal() bool {
	fi, err := os.Stdout.Stat()
	return err == nil && fi.Mode()&os.ModeCharDevice != 0
}

// writeTaskFile creates TASK.md in the workspace root with the assessment brief.
// No title heading: assessment titles are auto-derived from upstream issue
// text which leaks the answer (see project_audit_may2026_results.md). The
// brief itself is the single source of truth for what the candidate must do.
func writeTaskFile(workspacePath string, session Session, brief string, timeLimitMinutes int) {
	if workspacePath == "" || brief == "" {
		return
	}

	var content strings.Builder
	content.WriteString("# Task\n\n")
	content.WriteString(brief)
	content.WriteString("\n")

	if timeLimitMinutes > 0 {
		content.WriteString(fmt.Sprintf("\n---\n\n**Time limit:** %d minutes\n", timeLimitMinutes))
	}

	if session.SetupInstructions != "" {
		content.WriteString(fmt.Sprintf("\n## Setup\n\n%s\n", session.SetupInstructions))
	}

	content.WriteString("\n---\n\n")
	content.WriteString("*This file was generated by Promptster. You can reference it anytime, or run `promptster brief` in your terminal.*\n")

	taskPath := filepath.Join(workspacePath, "TASK.md")
	// Don't overwrite if it already exists (candidate might have edited it)
	if _, err := os.Stat(taskPath); err == nil {
		return
	}
	_ = os.WriteFile(taskPath, []byte(content.String()), 0o644)
}
